### ISSUE TITLE
无法兼容xcode 10

### ISSUE THREAD

**Issue by SoonKong** [qiyukf/QIYU_iOS_SDK#8]
原本在xcode9可以运行的项目，在xcode时上报错  
ld: library not found for -lstdc++.6.0.9
clang: error: linker command failed with exit code 1 (use -v to see invocation)

找了很久，发现貌似Xcode10已经找不到libstdc++6.0.9.tbd这个库了，而七鱼SDK引用到了；麻烦赶紧处理，更新个版本

**Comment by CoderHRXu** [comment]
> 原本在xcode9可以运行的项目，在xcode时上报错
> ld: library not found for -lstdc++.6.0.9
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 找了很久，发现貌似Xcode10已经找不到libstdc++6.0.9.tbd这个库了，而七鱼SDK引用到了；麻烦赶紧处理，更新个版本
可以根据这个 https://www.jianshu.com/p/3afd5e8cdbf8 临时凑合一下

**Comment by qiyukf** [comment]
您好，感谢您的反馈！我们会在下个版本修复此问题，并在开发指南中增加说明；4.5.0版本会在10月9日上线，届时还请您关注更新，谢谢！




| |
yunshangfu
|
|
邮箱：yunshangfu@126.com
|

Signature is customized by Netease Mail Master

在2018年09月19日 23:14，无风的秋 写道：

原本在xcode9可以运行的项目，在xcode时上报错
ld: library not found for -lstdc++.6.0.9
clang: error: linker command failed with exit code 1 (use -v to see invocation)

找了很久，发现貌似Xcode10已经找不到libstdc++6.0.9.tbd这个库了，而七鱼SDK引用到了；麻烦赶紧处理，更新个版本
可以根据这个 https://www.jianshu.com/p/3afd5e8cdbf8 临时凑合一下
