### ISSUE TITLE
skd版本4.10.0 linker错误

### ISSUE THREAD

**Issue by XueYangLee** [qiyukf/QIYU_iOS_SDK#9]
![image](https://user-images.githubusercontent.com/16890697/55207601-cab28a00-5215-11e9-9209-e980c8e5ea77.png)
同样项目在新电脑上拉去后报错，检查配置均正常，新电脑pods更新在最新 skd版本4.10.0，  后将sdk指定到上个版本恢复正常

**Comment by qiyukf** [comment]
您好，针对新版本Pods更新问题我们提供了如下解决方案：




| |
yunshangfu
|
|
邮箱：yunshangfu@126.com
|

Signature is customized by Netease Mail Master

在2019年03月29日 11:33，XueYangLee 写道：


同样项目在新电脑上拉去后报错，检查配置均正常，新电脑pods更新在最新 skd版本4.10.0， 后将sdk指定到上个版本恢复正常

**Comment by Liaosipei** [comment]
您好，针对新版本pods更新问题，我们提供以下解决方案：

**【现象】**
最近有好几家客户反馈使用CocoaPods更新SDK，更新后工程编译出错，我这边试验了一下，确实用Pods下载下来的SDK中，三个.a文件均有问题，大小只有100多字节，但我们的.a文件真实大小是：libQYSDK.a - 105.5M；libcrypto.a - 21.1M；libevent.a - 2.3M（在Mac上看的大小，别的系统上看到的可能有点儿差别）；也就是客户用Pods更新SDK，结果下载的.a文件不是完整文件，导致编译出现问题。
**【原因】**
在本次Pods更新中，我发现咱们的libQYSDK.a的大小超过了100M，Git不允许提交100M以上的文件（Pods更新SDK的本质其实是从对应的Git仓库中下载文件）；Git官方给出的解决办法是安装Git LFS（Large File Storage）服务，并将大的.a文件上传至Git LFS存储。于是，我按照官方解决办法使用了LFS服务，然后更新了Pods，但没有考虑到客户下载的时候，需要从Git LFS下载大文件，要求客户电脑也必须安装Git LFS服务才可以下载，也就造成普通下载时只下载了100多字节的文件，编译出现问题。不过，频繁使用Pods的客户迟早是要安装Git LFS的，以后SDK越来越大，总会遇到需要下载100M以上文件的时候。
**【问题定位】**
若有客户反馈更新完SDK后编译出问题，先询问是从官网下载的SDK还是Pods更新的SDK，如果是Pods更新的，问问下载下来的SDK中.a文件大小是不是以下大小：libQYSDK.a - 105.5M；libcrypto.a - 21.1M；libevent.a - 2.3M；如果大小明显有问题，就基本上可以定位是此问题，需要客户安装Git LFS来下载大文件。
**【解决方案】**
**安装Git LFS**，需注意，Git版本应不低于1.8.5，Mac上可以使用HomeBrew安装：
**1、安装HomeBrew：_/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"_
2、安装Git LFS：_brew install git-lfs_
3、启动Git LFS：_git lfs install_**
其他系统安装方法可参考 https://www.jianshu.com/p/493b81544f80 。注意，安装后重新_pod update_，若还是不行，需要清理：_pod cache clean --all_
**【相关说明】**
Git LFS相关说明可以参考：
1、https://www.jianshu.com/p/493b81544f80
2、https://zzz.buzz/zh/2016/04/19/the-guide-to-git-lfs/

**Comment by Liaosipei** [comment]
您好，针对新版本pods更新问题，我们提供以下解决方案：

**【现象】**
最近有好几家客户反馈使用CocoaPods更新SDK，更新后工程编译出错，我这边试验了一下，确实用Pods下载下来的SDK中，三个.a文件均有问题，大小只有100多字节，但我们的.a文件真实大小是：libQYSDK.a - 105.5M；libcrypto.a - 21.1M；libevent.a - 2.3M（在Mac上看的大小，别的系统上看到的可能有点儿差别）；也就是客户用Pods更新SDK，结果下载的.a文件不是完整文件，导致编译出现问题。
**【原因】**
在本次Pods更新中，我发现咱们的libQYSDK.a的大小超过了100M，Git不允许提交100M以上的文件（Pods更新SDK的本质其实是从对应的Git仓库中下载文件）；Git官方给出的解决办法是安装Git LFS（Large File Storage）服务，并将大的.a文件上传至Git LFS存储。于是，我按照官方解决办法使用了LFS服务，然后更新了Pods，但没有考虑到客户下载的时候，需要从Git LFS下载大文件，要求客户电脑也必须安装Git LFS服务才可以下载，也就造成普通下载时只下载了100多字节的文件，编译出现问题。不过，频繁使用Pods的客户迟早是要安装Git LFS的，以后SDK越来越大，总会遇到需要下载100M以上文件的时候。
**【问题定位】**
若有客户反馈更新完SDK后编译出问题，先询问是从官网下载的SDK还是Pods更新的SDK，如果是Pods更新的，问问下载下来的SDK中.a文件大小是不是以下大小：libQYSDK.a - 105.5M；libcrypto.a - 21.1M；libevent.a - 2.3M；如果大小明显有问题，就基本上可以定位是此问题，需要客户安装Git LFS来下载大文件。
**【解决方案】**
**安装Git LFS**，需注意，Git版本应不低于1.8.5，Mac上可以使用HomeBrew安装：
**1、安装HomeBrew：_/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"_
2、安装Git LFS：_brew install git-lfs_
3、启动Git LFS：_git lfs install_**
其他系统安装方法可参考 https://www.jianshu.com/p/493b81544f80 。注意，安装后重新_pod update_，若还是不行，需要清理：_pod cache clean --all_
**【相关说明】**
Git LFS相关说明可以参考：
1、https://www.jianshu.com/p/493b81544f80
2、https://zzz.buzz/zh/2016/04/19/the-guide-to-git-lfs/

**Comment by dengchaojie** [comment]
安装Git LFS：brew install git-lfs，重新 pod update，之后可以了。
